# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb087c8f6a507dd4e131b89145a768802b1d6e8107281096eba44cc21cbc1a148e32f3e73355a3f823cf2993e9c0c1f2fbd44ab73b02a3f2b33c53574ac25772

test:
  secret_key_base: ee456a1e230a7021122fb6af44b94100c509fdfe97cf5c62f518c45358022ba623cb5715d970b2b0dea71cb5aac100b8de56de02cdbdca33d76e62ded5dcb54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
